FROM python:3.12.4-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install cryptography
COPY . .
EXPOSE 4200
ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0","--port=4200"]
