version: '3.8'

services:
  web:
    build: .
    container_name: flaskapi-container  
    ports:
      - "4200:4200"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql-container 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=flet_crud_db
  