version: '3.8'

services:
  web:
    build: .
    container_name: flaskusers-container  
    ports:
      - "4300:4300"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql-container 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=flet_crud_db
  